import type {CellValue,ParsedPoll,PollTable,TableParty,ValidationResult} from "./types";
export const createId=(p="id")=>`${p}-${crypto.randomUUID()}`;
export function normalizePartyName(name:string){return name.trim().replace(/[״”"']/g,"").replace(/\s+/g," ").toLocaleLowerCase("he").replace(/^הרשימה\s+/,"").replace(/^מפלגת\s+/,"")}
export function displayPartyName(name:string){const n=normalizePartyName(name); const a:Record<string,string>={"שס":"ש״ס","רעמ":"רע״ם","הרשימה המשותפת":"המשותפת","ישר":"ישר!"}; return a[n]??name.trim()}
export function validatePoll(poll:{id:string;source:string;parties:{seats:CellValue}[]}):ValidationResult{const total=poll.parties.reduce((s,p)=>s+(p.seats??0),0);return{pollId:poll.id,source:poll.source,total,valid:total===120,missing:Math.max(120-total,0),excess:Math.max(total-120,0)}}
export function validateTable(t:PollTable){return t.polls.map(p=>{const total=t.parties.reduce((s,x)=>s+(x.values[p.id]??0),0);return{pollId:p.id,source:p.source,total,valid:total===120,missing:Math.max(120-total,0),excess:Math.max(total-120,0)}})}
export const allValid=(t:PollTable)=>validateTable(t).every(x=>x.valid);
export function mergePolls(table:PollTable|null,incoming:ParsedPoll[]):PollTable{const next:PollTable=table?structuredClone(table):{version:1,title:"סיכום סקרי השבוע",polls:[],parties:[]}; const by=new Map(next.parties.map(p=>[normalizePartyName(p.name),p])); for(const poll of incoming){const pollId=createId("poll");next.polls.push({id:pollId,source:poll.source.trim()});for(const raw of poll.parties){const key=normalizePartyName(raw.name);let party=by.get(key);if(!party&&key===normalizePartyName("הרשימה המשותפת"))party=by.get(normalizePartyName("המשותפת"));if(!party){party={id:createId("party"),name:displayPartyName(raw.name),values:{}};next.parties.push(party);by.set(key,party)}party.values[pollId]=raw.seats}for(const p of next.parties)if(!(pollId in p.values))p.values[pollId]=null}for(const p of next.parties)for(const poll of next.polls)if(!(poll.id in p.values))p.values[poll.id]=null;return next}
export function sortPartiesByFirstPoll(t:PollTable){const id=t.polls[0]?.id;if(!id)return t;return {...t,parties:[...t.parties].sort((a,b)=>(b.values[id]??-1)-(a.values[id]??-1))}}
